apiVersion: v1
kind: Service
metadata:
  name: backend-apifox-service
spec:
  selector:
    run: backend
  ports:
    - protocol: TCP
      nodeport: 30000
      port: 80
      targetPort: 8080
  type: NodePort
